version: '3.8'
services:
  python-script:
    container_name: subitosearchertelegrambot
    build: 
      context: .
      network: host  # <--- Fondamentale: permette al Dockerfile di scaricare pacchetti
    restart: unless-stopped
    network_mode: "host" # Mantiene la rete host anche durante l'esecuzione
    volumes: # source:destination # ./ relative / absolute
      - type: bind
        source: /DATA/AppData/subitosearchertelegrambot  # <host_path> suitable for CasaOS
        target: /app     # <container_path>
